package test

import (
	"context"
	"testing"

	"github.com/dolphindb/api-go/v3/api"
	"github.com/dolphindb/api-go/v3/test/setup"
	. "github.com/smartystreets/goconvey/convey"
)

var host5 = getRandomClusterAddress()
var ddb, _ = api.NewSimpleDolphinDBClient(context.TODO(), host5, setup.UserName, setup.Password)

func Test_DropPartition_tabletMultiple_range_drop_single(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_range_drop_single:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_range_drop_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			// rs, err := LoadTableBySQL(ddb, "10001", "select * from loadTable('"+DfsDBPath+"','"+DfsTBName1+"') where id >= %s", DfsDBPath, DfsTBName1)

			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where id >= 10001"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("'/1_10001'"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_range_drop_all_tables:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where id >= 10001"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("'/1_10001'"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("'/1_10001'"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_range_drop_multiple(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_range_drop_multiple:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_range_drop_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where id >= 30001"))
			So(err, ShouldBeNil)
			// err = DropPartition(ddb, DfsTBName1, DfsDBPath, `['/1_10001', '/10001_20001', '/20001_30001']`)

			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("['/1_10001', '/10001_20001', '/20001_30001']"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_range_drop_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where id >=30001"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("['/1_10001', '/10001_20001', '/20001_30001']"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("['/1_10001', '/10001_20001', '/20001_30001']"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}

func Test_DropPartition_tabletMultiple_hash_drop_single(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_hash_drop_single:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_hash_drop_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsHashdb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where id !=10"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("'/Key0'"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_hash_drop_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsHashdb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where id !=10"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("'/Key0'"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("'/Key0'"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_hash_drop_multiple(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_hash_drop_multiple:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_hash_drop_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsHashdb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where id in 2..9"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("['/Key0', '/Key1']"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_hash_drop_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ExistsDatabase(ddb, DfsDBPath)
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsHashdb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ExistsDatabase(ddb, DfsDBPath)
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := LoadTable(ddb, DfsTBName1, DfsDBPath)
			So(err, ShouldBeNil)
			originTable2, err := LoadTable(ddb, DfsTBName1, DfsDBPath)
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := LoadTableBySQL(ddb, "2..9", "select * from loadTable('"+DfsDBPath+"','"+DfsTBName1+"') where id in %s", DfsDBPath, DfsTBName1)
			So(err, ShouldBeNil)
			err = DropPartition(ddb, DfsTBName1, DfsDBPath, `['/Key0', '/Key1']`)
			So(err, ShouldBeNil)
			err = DropPartition(ddb, DfsTBName2, DfsDBPath, `['/Key0', '/Key1']`)
			So(err, ShouldBeNil)
			reTable1, err := LoadTable(ddb, DfsTBName1, DfsDBPath)
			So(err, ShouldBeNil)
			reTable2, err := LoadTable(ddb, DfsTBName2, DfsDBPath)
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = DropDatabase(ddb, DfsDBPath)
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_value_drop_single(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_value_drop_single:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_value_drop_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsValuedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date !=2010.01.01"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("'/20100101'"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_value_drop_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsValuedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date !=2010.01.01"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("'/20100101'"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("'/20100101'"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_value_drop_multiple(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_value_drop_multiple:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_value_drop_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsValuedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where!in(date, 2010.01.01+[0, 7, 14, 21])"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("['/20100101', '/20100108', '/20100115', '/20100122']"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_value_drop_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsValuedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where!in(date, 2010.01.01+[0, 7, 14, 21])"))
			So(err, ShouldBeNil)

			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("['/20100101', '/20100108', '/20100115', '/20100122']"))
			So(err, ShouldBeNil)

			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("['/20100101', '/20100108', '/20100115', '/20100122']"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_list_drop_single(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_list_drop_single:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_list_drop_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsListdbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where!in(sym,`AMD`QWE`CES)"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("'/List0'"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_list_drop_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsListdbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where!in(sym,`AMD`QWE`CES)"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("'/List0'"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("'/List0'"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_list_drop_multiple(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_list_drop_multiple:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_list_drop_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsListdbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where!in(sym,`DOP`ASZ`FSD`BBVC)"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("['/List1', '/List2']"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_list_drop_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsListdbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where!in(sym,`DOP`ASZ`FSD`BBVC)"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("['/List1', '/List2']"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("['/List1', '/List2']"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_compo_range_range_drop_level1_single(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level1_single:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level1_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date >=2010.02.01"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("2010.01.01"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level1_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date >=2010.02.01"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("2010.01.01"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("2010.01.01"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_compo_range_range_drop_level1_multiple(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level1_multiple:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level1_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date >=2010.03.01"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("[2010.01.01, 2010.02.01]"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level1_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date >=2010.03.01"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("[2010.01.01, 2010.02.01]"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("[2010.01.01, 2010.02.01]"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_compo_range_range_drop_level2_single(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level2_single:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level2_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date >=2010.02.01 or id >= 3"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("[2010.01.01, 1]"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level2_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date >=2010.02.01 or id >= 3"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths("[2010.01.01, 1]"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths("[2010.01.01, 1]"))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
func Test_DropPartition_tabletMultiple_compo_range_range_drop_level2_multiple(t *testing.T) {
	t.Parallel()
	Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level2_multiple:", t, func() {
		Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level2_only_one_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date >=date >= 2010.03.01 or !between(id, 3:6)"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths(`[[2010.01.01,2010.02.01], [3,5]]`))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, originTable2)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
		Convey("Test_DropPartition_tabletMultiple_compo_range_range_drop_level2_all_table:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedbChunkGranularity(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(new(api.ExistsDatabaseRequest).SetPath(DfsDBPath))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			originTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			originTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			re := CompareTables(originTable1, originTable2)
			So(err, ShouldBeNil)
			So(re, ShouldBeTrue)
			rs, err := ddb.LoadTableBySQL(new(api.LoadTableBySQLRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetSQL("select * from loadTable('" + DfsDBPath + "','" + DfsTBName1 + "') where date >=date >= 2010.03.01 or !between(id, 3:6)"))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1).SetPartitionPaths(`[[2010.01.01,2010.02.01], [3,5]]`))
			So(err, ShouldBeNil)
			err = ddb.DropPartition(new(api.DropPartitionRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName2).SetPartitionPaths(`[[2010.01.01,2010.02.01], [3,5]]`))
			So(err, ShouldBeNil)
			reTable1, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			reTable2, err := ddb.LoadTable(new(api.LoadTableRequest).SetDatabase(DfsDBPath).SetTableName(DfsTBName2))
			So(err, ShouldBeNil)
			reData1 := CompareTables(reTable1, rs)
			So(reData1, ShouldBeTrue)
			reData2 := CompareTables(reTable2, rs)
			So(reData2, ShouldBeTrue)
			err = ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
		})
	})
}
