package test

import (
	"context"
	"testing"

	"github.com/dolphindb/api-go/v3/api"
	"github.com/dolphindb/api-go/v3/test/setup"
	. "github.com/smartystreets/goconvey/convey"
)

var host7 = getRandomClusterAddress()

func TestExistDatabaseAndDropDatabase(t *testing.T) {
	t.Parallel()
	Convey("Test ExistDatabase and dropDatabase prepare", t, func() {
		ddb, err := api.NewSimpleDolphinDBClient(context.TODO(), host7, setup.UserName, setup.Password)
		So(err, ShouldBeNil)
		Convey("Test_ExistDatabase_wrong_db_exception", func() {
			res, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: "adgasw"})
			So(res, ShouldBeFalse)
			So(err, ShouldBeNil)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_dimension:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsDimensiondb(DfsDBPath, TbName1, TbName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_range:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsRangedb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_hash:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsHashdb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_value:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsValuedb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_list:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsListdb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_compo_range_range:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_compo_range_value:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeValuedb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_compo_range_list:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeListdb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_dfs_compo_range_hash:", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeHashdb(DfsDBPath, DfsTBName1, DfsTBName2)
			re2, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DfsDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_disk_unpartitioned_table:", func() {
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskUnpartitioneddb(DiskDBPath, TbName1, TbName2)
			re2, err := ddb.ExistsTable(&api.ExistsTableRequest{TableName: TbName1, DBPath: DiskDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DiskDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_create_disk_range_db:", func() {
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskRangedb(DiskDBPath, TbName1, TbName2)
			re2, err := ddb.ExistsTable(&api.ExistsTableRequest{TableName: TbName1, DBPath: DiskDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DiskDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_create_disk_hash_db:", func() {
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskHashdb(DiskDBPath, TbName1, TbName2)
			re2, err := ddb.ExistsTable(&api.ExistsTableRequest{TableName: TbName1, DBPath: DiskDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DiskDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_create_disk_value_db:", func() {
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskValuedb(DiskDBPath, TbName1, TbName2)
			re2, err := ddb.ExistsTable(&api.ExistsTableRequest{TableName: TbName1, DBPath: DiskDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DiskDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_create_disk_list_db:", func() {
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskListdb(DiskDBPath, TbName1, TbName2)
			re2, err := ddb.ExistsTable(&api.ExistsTableRequest{TableName: TbName1, DBPath: DiskDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DiskDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_ExistDatabase_and_dropDatabase_create_compo_range_range_db:", func() {
			re1, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskCompoRangeRangedb(DiskDBPath, TbName1, TbName2)
			re2, err := ddb.ExistsTable(&api.ExistsTableRequest{TableName: TbName1, DBPath: DiskDBPath})
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DiskDBPath})
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsDatabase(&api.ExistsDatabaseRequest{Path: DiskDBPath})
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
	})
}
