package test

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/dolphindb/api-go/v3/api"
	"github.com/dolphindb/api-go/v3/test/setup"
	. "github.com/smartystreets/goconvey/convey"
)

var host8 = getRandomClusterAddress()

func TestDropTableException(t *testing.T) {
	t.Parallel()
	Convey("Test_existsTable_and_dropTable_prepare", t, func() {
		ddb, err := api.NewSimpleDolphinDBClient(context.TODO(), host8, setup.UserName, setup.Password)
		So(err, ShouldBeNil)
		Convey("Test_dropTable_wrong_Table_exception", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(&api.ExistsTableRequest{DBPath: DfsDBPath, TableName: TbName1})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsDimensiondb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(TbName1).SetDBPath(DfsDBPath))
			So(err, ShouldNotBeNil)
		})
		Convey("Test_dropTable_wrong_dbpath_exception", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(&api.ExistsTableRequest{DBPath: DfsDBPath, TableName: TbName1})
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsDimensiondb(DfsDBPath, TbName1, TbName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			err = ddb.DropTable(&api.DropTableRequest{TableName: TbName1, DBPath: "dfs://wrong_dbpath"})
			So(err, ShouldNotBeNil)
		})
		Convey("Test_dropTable_only_DBHandle_dbPath_exception", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			ddbScript := `
			dbPath="` + DfsDBPath + `"
			if(existsDatabase(dbPath))
					dropDatabase(dbPath)
			db=database(dbPath, RANGE, 1..10)
			n=100000
			tdata=table(sort(take(2010.01.01..2010.12.31, n)) as date, 1..n as id, take(["AMD", "QWE", "CES", "DOP", "ASZ", "FSD", "BBVC", "AWQ", "DS"], n) as sym, rand(100, n) as val)
			db.createTable(tdata, "` + DfsTBName1 + `").append!(tdata)
			db.createTable(tdata, "` + DfsTBName2 + `").append!(tdata)
			`
			_, err = ddb.RunScript(ddbScript)
			defer ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DfsDBPath))
			So(err, ShouldBeNil)
			t := new(api.DropTableRequest).
				SetDBPath(DfsDBPath).SetDBHandle("db")
			err = ddb.DropTable(t)
			So(err, ShouldNotBeNil)
		})
		err = ddb.Close()
		So(err, ShouldBeNil)
	})
}

func TestExistsTableAndDropTable(t *testing.T) {
	t.Parallel()
	Convey("Test_existsTable_and_dropTable_prepare", t, func() {
		ddb, err := api.NewSimpleDolphinDBClient(context.TODO(), host8, setup.UserName, setup.Password)
		So(err, ShouldBeNil)
		Convey("Test_existsTable_dropDatabase", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			dbPaths := []string{DfsDBPath, DiskDBPath}
			for _, dbPath := range dbPaths {
				script := `
				if(existsDatabase("` + dbPath + `")){
					dropDatabase("` + dbPath + `")
				}
				if(exists("` + dbPath + `")){
					rmdir("` + dbPath + `", true)
				}
				`
				_, err = ddb.RunScript(script)
				So(err, ShouldBeNil)
			}
		})
		Convey("Test_existsTable_dfs_dimension", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(TbName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(TbName2))
			So(err, ShouldBeNil)
			So(re2, ShouldBeFalse)
			CreateDfsDimensiondb(DfsDBPath, TbName1, TbName2)
			time.Sleep(10 * time.Second)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(TbName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeTrue)
			re4, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(TbName2))
			So(err, ShouldBeNil)
			So(re4, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(TbName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(TbName2).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re5, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(TbName1))
			So(err, ShouldBeNil)
			So(re5, ShouldBeFalse)
			re6, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(TbName2))
			So(err, ShouldBeNil)
			So(re6, ShouldBeFalse)
		})
		Convey("Test_existsTable_dfs_value", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsValuedb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_dfs_range", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsRangedb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_dfs_hash", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsHashdb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_dfs_list", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsListdb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_dfs_compo_range_range", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeRangedb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_dfs_compo_range_value", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeValuedb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_dfs_compo_range_list", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeListdb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_dfs_compo_range_hash", func() {
			DfsDBPath := "dfs://" + generateRandomString(8)
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDfsCompoRangeHashdb(DfsDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(&api.DropDatabaseRequest{Directory: DfsDBPath})
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DfsDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_disk_unpartitioned_table", func() {
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DfsDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskUnpartitioneddb(DiskDBPath, TbName1, TbName2)
			defer ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DiskDBPath))
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(TbName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(TbName1).SetDBPath(DiskDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName("tdata"))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_disk_range", func() {
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskRangedb(DiskDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DiskDBPath))
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DiskDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_disk_value", func() {
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskValuedb(DiskDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DiskDBPath))
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DiskDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_disk_list", func() {
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskListdb(DiskDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DiskDBPath))
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DiskDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_disk_hash", func() {
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskHashdb(DiskDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DiskDBPath))
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DiskDBPath))
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
		Convey("Test_existsTable_disk_compo_range_range", func() {
			re1, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re1, ShouldBeFalse)
			CreateDiskCompoRangeRangedb(DiskDBPath, DfsTBName1, DfsTBName2)
			defer ddb.DropDatabase(new(api.DropDatabaseRequest).SetDirectory(DiskDBPath))
			re2, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re2, ShouldBeTrue)
			err = ddb.DropTable(new(api.DropTableRequest).SetTableName(DfsTBName1).SetDBPath(DiskDBPath))
			fmt.Println(err)
			So(err, ShouldBeNil)
			re3, err := ddb.ExistsTable(new(api.ExistsTableRequest).SetDBPath(DiskDBPath).SetTableName(DfsTBName1))
			So(err, ShouldBeNil)
			So(re3, ShouldBeFalse)
		})
	})
}
