run:
  skip-dirs:
  - test
  - performance
  - example
linters-settings:
  stylecheck:
    # Select the Go version to target.
    # Default: 1.13
    go: "1.15"
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    # https://staticcheck.io/docs/options#dot_import_whitelist
    dot-import-whitelist:
      - fmt
    # https://staticcheck.io/docs/options#initialisms
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS"]
    # https://staticcheck.io/docs/options#http_status_code_whitelist
    http-status-code-whitelist: ["200", "400", "404", "500"]
linters:
  enable-all: true
  disable:
    - wrapcheck
    - ireturn
    - dupl
    - varnamelen
    - gosec
    - gocyclo
    - stylecheck
    - nlreturn
    - gochecknoglobals
    - goerr113
    - gomnd
    - maintidx
    - gofumpt
    - gci
    - gocritic
    - forcetypeassert
    - exhaustivestruct
    - exhaustruct
    - exhaustive
    - cyclop
    - containedctx
    - wsl
    - paralleltest
    - testpackage
    - maligned
    - gocognit
    - forbidigo
    - nestif
    - lll
    - funlen
    - godox
    - scopelint
    - golint
    - interfacer
    - ifshort